src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 * 
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * 
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention la date d'arrive doit etre au bon format")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention la date de depart doit etre au bon format")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Undocumented function
     * @ORM\PrePersist
     * @return void
     */
    public function prePersist(){
        if( empty( $this->createAt ) ){
                $this->createAt = new \DateTime();
        }

        if( empty( $this->amount ) ){
            $this->amount = $this->getDuration() * $this->ad->getPrice();
        }
    }

    public function getDuration(){
        $diff = $this->endDate->diff( $this->startDate );
        return $diff->days;
    }

    public function isbookableDate(){

        //Il faut connaitre les dates qui sont impossible pour l'annonce
        $notAvailableDays = $this->ad->getNotAvailableDays();

        //il faut comparer les dates choisie avec les dates impossible
        $bookingDays = $this->getDays();

        //Tableau de chaine de caractere de mes journees
        $days = array_map( function($days){
            return $days->format('Y-m-d');
        },$bookingDays );

        $notAvailable = array_map(function($days){
            return $days->format('Y-m-d');
        }, $notAvailableDays);

        foreach ($days as $day){
            if( array_search( $day,$notAvailable ) !== false ) return false;
        }
        return true;
    }
    /**
     * Undocumented function
     *
     * @return Array
     */
    public function getDays(){

        $resultat = range( $this->startDate->getTimestamp(),
                           $this->endDate->getTimestamp(),
                           24 * 60 * 60
                        );
        $days = array_map( function( $dayTimeStamp ){
                return new \DateTime( date( 'Y-m-d',$dayTimeStamp ) );
                }, $resultat );
        return $days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?Users
    {
        return $this->booker;
    }

    public function setBooker(?Users $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"}, 
 *  message="Cet email existe deja."
 * )
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez rensegner un email")
     */
    private $email;

    /**
     * @ORM\Column( type="string", length=255, nullable=true )
     * @Assert\Url()
     */
    private $picture;

    /**
     * @ORM\Column( type="string", length=255 )
     */
    private $hash;

    /**
     * @Assert\EqualTo( propertyPath="hash" )
     */

    public $passwordConfirm;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    /**
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initialyzeSlug(){
        if( empty($this->slug)) {
            $slugly = new Slugify();
            $this->slug = $slugly->slugify($this->lastname . ' ' . $this->firstname);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(){
        return "$this->firstname $this->lastname";
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles(){

        $roles = $this->userRoles->map(function($role){return $role->getTitle();})->toArray();
        $roles[] = 'ROLE_USER';
        return $roles;
    }

    public function getPassword(){
        return $this->getHash();
    }

    public function getSalt(){}

    public function getUsername(){
        return $this->getEmail();
    }

    public function eraseCredentials(){}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer){

        $this->transformer = $transformer;
    }

    public function buildForm( FormBuilderInterface $builder, array $options )
    {
        $builder
            ->add( 'startDate', TextType::class, $this->getConfiguration( "Date d'arrivée", "La date à laquelle vous comptez arriver" ) )
            ->add( 'endDate',  TextType::class, $this->getConfiguration( "Date de départ", "La date à laquelle vous comptez partir" ) )
            ->add( 'comment', TextareaType::class, $this->getConfiguration( false, "Quelque chose a dire ?", ["required" => false]) );
            $builder->get('startDate')->setModelTransformer($this->transformer);
            $builder->get('endDate')->setModelTransformer($this->transformer);
        }

    public function configureOptions( OptionsResolver $resolver )
    {
        $resolver->setDefaults( [
            'data_class' => Booking::class,
        ] );
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function book( Ad $ad, Request $request, ObjectManager $manager )
    {
        $booking = new Booking();
        $form = $this->createForm( BookingType::class, $booking );

        $form->handleRequest($request);

        if( $form->isSubmitted() && $form->isValid() ){

            $user = $this->getUser();

            $booking->setBooker( $user )
                    ->setAd( $ad );
            
                    if( !$booking->isbookableDate() ){
                        $this->addFlash( 'warning',
                                         'Les dates choisie pour votre sejour sont deja prise'
                                       );
                    }else{
                        $manager->persist( $booking );
                        $manager->flush();

                    return $this->redirectToRoute( 'booking_show', [ 'id' => $booking->getId(), 'withAlert' => true ] );
                    }  
                    }
           
        
        return $this->render( 'booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Undocumented function
     *
     * @Route("/booking/{id}", name="booking_show")
     * @param Booking $booking
     * @return Response
     */
    public function show( Booking $booking ){
        
       return $this->render( 'booking/show.html.twig', [ 'booking' => $booking ] );

    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
{% endblock %}
{% block title %}Réserver l'annonce: {{ ad.title }} !{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réserver l'annonce: {{ ad.title }}</h1>
        <p>
        Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.FullName }}</strong>, dite nous tous, on s'occuper du reste!
        </p>
        {{ form_start( form ) }}
        <div class="alert alert-light">
            <h2>Commencez par nous dire quelles sont les dates qui  vous intérressent !</h2>
            <div class="row">
                <div class="col">{{ form_row( form.startDate ) }}</div>
                <div class="col">{{ form_row( form.endDate ) }}</div>
            </div>
        </div>
        <h4>Montant du séjour: <span id="amout">..</span> &euro;</h4>
        <span id="days">0</span> nuit(s) à {{ ad.price }} / nuit

        <h2>Vous avez un commentaire</h2>
        {{ form_row( form.comment ) }}

        <h2>Vous avez termine !</h2>
        <button type="submit" class="btn btn-success">Je reserve !</button>
        {{ form_end( form ) }}
    </div>
{% endblock %}
{% block javascripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>
<script>
 $('#booking_startDate,#booking_endDate').datepicker({
     format: 'dd/mm/yyyy',
     datesDisabled: [
         {% for day in ad.notAvailableDays%}
            "{{ day.format('d/m/Y') }}",
         {% endfor %}
     ],
     startDate: new Date
 });
   
</script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation N: {{ booking.id }}{% endblock %}

{% block body %}
<div class="container">
    <h1>Votre réservation N: {{ booking.id }}</h1>
    {% if app.request.query.get('withAlert') %}
        <div class="alert alert-success">
            <h4 class="alert-heading">Bravo !</h4>
            <p>Votre reservation aupres de {{ booking.ad.author.fullName }} a bien ete prise en compte.</p>
        </div>
    {% endif %}
    <div class="col-5">
        <div class="alert alert-light">
            <h2>Detail</h2>
                <dl class="row">
                    <dt class="col-md-4">Numeros</dt>
                    <dd class="col-md-8">{{ booking.id }}</dd>
                    <dt class="col-md-4">date d arriver</dt>
                    <dd class="col-md-8">{{ booking.startDate | date( 'd/m/y' ) }}</dd>
                    <dt class="col-md-4">Date de depart</dt>
                    <dd class="col-md-8">{{ booking.endDate | date( 'd/m/y' ) }}</dd>
                    <dt class="col-md-4">Nombre de nuit</dt>
                    <dd class="col-md-8">{{ booking.duration }}</dd>
                    <dt class="col-md-4">Montant Total</dt>
                    <dd class="col-md-8">{{ booking.amount }}</dd>
                    <dt class="col-md-4">Commentaire</dt>
                    <dd class="col-md-8">{{ booking.comment }}</dd>
                </dl>
                <hr>
                <h2 class="alert-heading">Votre hote</h2>
            <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{ booking.ad.author.picture }}" alt="Avatar de {{ booking.ad.author.fullName }}" class="avatar avatar-medium">
                    </div>
                    <div class="col-9">
                        <h4><a href="{{ path( 'user_show', { 'slug': booking.ad.author.slug } ) }}">{{ booking.ad.author.fullName }}</a></h4>
                        <span class="badge badge-primary">{{ booking.ad.author.ads | length }} annonces</span>
                    </div>
            </div>
            {{ booking.ad.author.description | raw }}
             <a href="{{ path( 'user_show', { 'slug': booking.ad.author.slug } ) }}" class="btn btn-primary">Plus d'info sur {{ booking.ad.author.lastName }}</a>
        </div>
    </div>
        <div class="col">
            <h2>Votre Hebergement</h2>
            <h4><a href="{{ path('ad_show', { 'slug': booking.ad.slug } ) }}" class=''>{{booking.ad.title}}</a></h4>
            <img src="{{ booking.ad.coverImage }}" alt="{{ booking.ad.title }}" class="img-fluid">
            {{ booking.ad.content | raw }}
            <a href="{{ path('ad_show', { 'slug': booking.ad.slug }) }}" class="btn btn-rimary">Plus d'information</a>
        </div>
    </div>
</div>

{% endblock %}